# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [1, 3, 4]
show_hidden = true

[preview]
max_width = 1200
max_height = 1800

[opener]
play = [
  { run = 'mpv --force-window %s', orphan = true, for = "unix" },
  { run = 'mpv --force-window %s', orphan = true, for = "windows" },
  { run = "mediainfo %s1; echo 'Press enter to exit'; read _", block = true, desc = "Show media info", for = "unix" },
]

[plugin]
prepend_fetchers = [
  { id = "git", url = "*", run = "git" },
  { id = "git", url = "*/", run = "git" },
]
prepend_previewers = [{ url = "*.ipynb", run = "nbpreview" }]
