EnableImagePreviewing: false
themes:
  - name: "theme-black-metal-mayhem"
    colors:
      - "#000000"
      - "#3f3f3f"
      - "#c1c1c1"
      - "#3f3f3f"
      - "#c1c1c1"
      - "#c1c1c1"
      - "#c1c1c1"
      - "#c1c1c1"
      - "#5f8787"
      - "#5f8787"
      - "#eecc6c"
      - "#f3ecd4"
      - "#aaaaaa"
      - "#888888"
      - "#999999"
      - "#999999"
  - name: "theme-broadcast"
    colors:
      - "#2b2b2b"
      - "#585858"
      - "#5a647e"
      - "#585858"
      - "#ffffff"
      - "#e6e1dc"
      - "#ffffff"
      - "#ffffff"
      - "#da4939"
      - "#ff7b6b"
      - "#ffd24a"
      - "#519f50"
      - "#6e9cbe"
      - "#6d9cbe"
      - "#d0d0ff"
      - "#d0d0ff"
  - name: "theme-carbonfox"
    colors:
      - "#161616"
      - "#1c1c1c"
      - "#252525"
      - "#7b7c7e"
      - "#b6b8bb"
      - "#f2f4f8"
      - "#ffffff"
      - "#c4c4c4"
      - "#EE5396"
      - "#3DDBD9"
      - "#08BDBA"
      - "#25be6a"
      - "#33B1FF"
      - "#78A9FF"
      - "#BE95FF"
      - "#FF7EB6"
  - name: "theme-charcoal-ember"
    colors:
      - "#1d1f21"
      - "#2d2d2d"
      - "#373b41"
      - "#969896"
      - "#969896"
      - "#c5c8c6"
      - "#e0e0e0"
      - "#ffffff"
      - "#c90d00"
      - "#f79802"
      - "#ffc400"
      - "#60b45a"
      - "#5fb3b3"
      - "#4eb6fe"
      - "#b294bb"
      - "#c09c24"
  - name: "theme-everforest-dark-hard"
    colors:
      - "#1e2326"
      - "#a6b0a0"
      - "#4c3743"
      - "#a6b0a0"
      - "#f2efdf"
      - "#d3c6aa"
      - "#fffbef"
      - "#fffbef"
      - "#e67e80"
      - "#f85552"
      - "#dbbc7f"
      - "#a7c080"
      - "#83c092"
      - "#7fbbb3"
      - "#d699b6"
      - "#d699b6"
  - name: "theme-flexoki-moon-black"
    colors:
      - "#100f0f"
      - "#1c1b1a"
      - "#282726"
      - "#575653"
      - "#878580"
      - "#cecdc3"
      - "#EDEECF"
      - "#ffffff"
      - "#d14d41"
      - "#da702c"
      - "#d0a215"
      - "#879a39"
      - "#3aa99f"
      - "#4385be"
      - "#8b7ec8"
      - "#ce5d97"
  - name: "theme-flexoki-moon-green"
    colors:
      - "#08120b"
      - "#151f18"
      - "#253426"
      - "#6b7d6e"
      - "#8f8a98"
      - "#ddd8e8"
      - "#d6fadc"
      - "#ffffff"
      - "#d14d41"
      - "#da702c"
      - "#d0a215"
      - "#879a39"
      - "#3aa99f"
      - "#4385be"
      - "#8b7ec8"
      - "#ce5d97"
  - name: "theme-flexoki-moon-purple"
    colors:
      - "#12101d"
      - "#1c1a25"
      - "#1f1d2a"
      - "#625f68"
      - "#8f8a98"
      - "#ddd8e8"
      - "#EDEECF"
      - "#ffffff"
      - "#d14d41"
      - "#da702c"
      - "#d0a215"
      - "#879a39"
      - "#3aa99f"
      - "#4385be"
      - "#8b7ec8"
      - "#ce5d97"
  - name: "theme-flexoki-moon-red"
    colors:
      - "#18090b"
      - "#251a1a"
      - "#3a2b28"
      - "#8a6b60"
      - "#b5967e"
      - "#f0e8dd"
      - "#ffeaec"
      - "#ffffff"
      - "#d14d41"
      - "#da702c"
      - "#d0a215"
      - "#879a39"
      - "#3aa99f"
      - "#4385be"
      - "#8b7ec8"
      - "#ce5d97"
  - name: "theme-flexoki-moon-toddler"
    colors:
      - "#2a1f16"
      - "#464132"
      - "#713d3a"
      - "#726250"
      - "#c4b199"
      - "#d4c4a8"
      - "#fff2d8"
      - "#ffffff"
      - "#dd634d"
      - "#d19812"
      - "#957209"
      - "#7eae0f"
      - "#4f7edc"
      - "#3672da"
      - "#be0033"
      - "#ca1447"
  - name: "theme-github-dark-default"
    colors:
      - "#0d1117"
      - "#161b22"
      - "#21262d"
      - "#8b949e"
      - "#6e7681"
      - "#e6edf3"
      - "#f0f6fc"
      - "#ffffff"
      - "#ff7b72"
      - "#ffa657"
      - "#f2cc60"
      - "#7ee787"
      - "#a5d6ff"
      - "#79c0ff"
      - "#d2a8ff"
      - "#f85149"
  - name: "theme-github-dark-dimmed"
    colors:
      - "#22272e"
      - "#2d333b"
      - "#373e47"
      - "#768390"
      - "#636e7b"
      - "#adbac7"
      - "#cdd9e5"
      - "#ffffff"
      - "#f47067"
      - "#e0823d"
      - "#c69026"
      - "#57ab5a"
      - "#96d0ff"
      - "#6cb6ff"
      - "#dcbdfb"
      - "#e5534b"
  - name: "theme-github-dark"
    colors:
      - "#101216"
      - "#4d4d4d"
      - "#3b5070"
      - "#4d4d4d"
      - "#ffffff"
      - "#8b949e"
      - "#ffffff"
      - "#ffffff"
      - "#f78166"
      - "#f78166"
      - "#e3b341"
      - "#56d364"
      - "#2b7489"
      - "#6ca4f8"
      - "#db61a2"
      - "#db61a2"
  - name: "theme-gruvbox-dark-hard"
    colors:
      - "#1d2021"
      - "#3c3836"
      - "#504945"
      - "#665c54"
      - "#928374"
      - "#ebdbb2"
      - "#d5c4a1"
      - "#fbf1c7"
      - "#fb4934"
      - "#fe8019"
      - "#fabd2f"
      - "#b8bb26"
      - "#8ec07c"
      - "#83a598"
      - "#d3869b"
      - "#d65d0e"
  - name: "theme-gruvbox-dark-medium"
    colors:
      - "#282828"
      - "#928374"
      - "#665c54"
      - "#928374"
      - "#a89984"
      - "#ebdbb2"
      - "#ebdbb2"
      - "#ebdbb2"
      - "#cc241d"
      - "#fb4934"
      - "#d79921"
      - "#98971a"
      - "#689d6a"
      - "#458588"
      - "#b16286"
      - "#b16286"
  - name: "theme-gruvbox"
    colors:
      - "#1d2021"
      - "#3c3836"
      - "#504945"
      - "#665c54"
      - "#928374"
      - "#ebdbb2"
      - "#d5c4a1"
      - "#fbf1c7"
      - "#fb4934"
      - "#fe8019"
      - "#fabd2f"
      - "#b8bb26"
      - "#8ec07c"
      - "#83a598"
      - "#d3869b"
      - "#d65d0e"
  - name: "theme-kanagawa"
    colors:
      - "#1f1f28"
      - "#16161d"
      - "#2d4f67"
      - "#727169"
      - "#c8c093"
      - "#dcd7ba"
      - "#c8c093"
      - "#717c7c"
      - "#c34043"
      - "#ffa066"
      - "#c0a36e"
      - "#76946a"
      - "#6a9589"
      - "#7e9cd8"
      - "#957fb8"
      - "#d27e99"
  - name: "theme-material-design-colors"
    colors:
      - "#1d262a"
      - "#a1b0b8"
      - "#4e6a78"
      - "#a1b0b8"
      - "#ffffff"
      - "#e7ebed"
      - "#ffffff"
      - "#ffffff"
      - "#fc3841"
      - "#fc746d"
      - "#fed032"
      - "#5cf19e"
      - "#59ffd1"
      - "#37b6ff"
      - "#fc226e"
      - "#fc226e"
  - name: "theme-nightfox"
    colors:
      - "#192330"
      - "#212e3f"
      - "#29394f"
      - "#738091"
      - "#71839b"
      - "#cdcecf"
      - "#d6d6d7"
      - "#aeafb0"
      - "#c94f6d"
      - "#f4a261"
      - "#dbc074"
      - "#81b29a"
      - "#63cdcf"
      - "#719cd6"
      - "#9d79d6"
      - "#d67ad2"
  - name: "theme-nordic"
    colors:
      - "#242933"
      - "#2E3440"
      - "#3B4252"
      - "#4C566A"
      - "#60728A"
      - "#BBC3D4"
      - "#D8DEE9"
      - "#E5E9F0"
      - "#BF616A"
      - "#D08770"
      - "#EBCB8B"
      - "#A3BE8C"
      - "#8FBCBB"
      - "#81A1C1"
      - "#B48EAD"
      - "#5E81AC"
  - name: "theme-oceanic-next"
    colors:
      - "#162c35"
      - "#65737e"
      - "#4f5b66"
      - "#65737e"
      - "#ffffff"
      - "#c0c5ce"
      - "#ffffff"
      - "#ffffff"
      - "#ec5f67"
      - "#ec5f67"
      - "#fac863"
      - "#99c794"
      - "#5fb3b3"
      - "#6699cc"
      - "#c594c5"
      - "#c594c5"
  - name: "theme-pandora"
    colors:
      - "#141e43"
      - "#3f5648"
      - "#2d37ff"
      - "#3f5648"
      - "#e2e2e2"
      - "#e1e1e1"
      - "#ffffff"
      - "#ffffff"
      - "#ff4242"
      - "#ff3242"
      - "#ffad29"
      - "#74af68"
      - "#23d7d7"
      - "#338f86"
      - "#9414e6"
      - "#9414e6"
  - name: "theme-popping-and-locking"
    colors:
      - "#181921"
      - "#928374"
      - "#ebdbb2"
      - "#928374"
      - "#a89984"
      - "#ebdbb2"
      - "#ebdbb2"
      - "#ebdbb2"
      - "#cc241d"
      - "#f42c3e"
      - "#d79921"
      - "#98971a"
      - "#689d6a"
      - "#458588"
      - "#b16286"
      - "#b16286"
  - name: "theme-raycast-dark"
    colors:
      - "#1a1a1a"
      - "#4c4c4c"
      - "#333333"
      - "#4c4c4c"
      - "#ffffff"
      - "#ffffff"
      - "#ffffff"
      - "#ffffff"
      - "#ff5360"
      - "#ff6363"
      - "#ffc531"
      - "#59d499"
      - "#52eee5"
      - "#56c2ff"
      - "#cf2f98"
      - "#cf2f98"
  - name: "theme-retro-legends"
    colors:
      - "#0d0d0d"
      - "#4c594c"
      - "#336633"
      - "#4c594c"
      - "#bfe6bf"
      - "#45eb45"
      - "#f2fff2"
      - "#f2fff2"
      - "#de5454"
      - "#ff6666"
      - "#f7bf2b"
      - "#45eb45"
      - "#40d9e6"
      - "#4066f2"
      - "#bf4cf2"
      - "#bf4cf2"
  - name: "theme-retrobox"
    colors:
      - "#1c1c1c"
      - "#3c3836"
      - "#504945"
      - "#928374"
      - "#a89984"
      - "#ebdbb2"
      - "#d5c4a1"
      - "#fbf1c7"
      - "#fb4934"
      - "#fe8019"
      - "#fabd2f"
      - "#b8bb26"
      - "#8ec07c"
      - "#83a598"
      - "#d3869b"
      - "#d65d0e"
  - name: "theme-rose-pine-darker"
    colors:
      - "#191724"
      - "#1f1d2e"
      - "#26233a"
      - "#6e6a86"
      - "#908caa"
      - "#e0def4"
      - "#e0def4"
      - "#524f67"
      - "#eb6f92"
      - "#f6c177"
      - "#ebbcba"
      - "#31748f"
      - "#9ccfd8"
      - "#c4a7e7"
      - "#f6c177"
      - "#524f67"
  - name: "theme-rose-pine-moon"
    colors:
      - "#232136"
      - "#6e6a86"
      - "#44415a"
      - "#6e6a86"
      - "#e0def4"
      - "#e0def4"
      - "#e0def4"
      - "#e0def4"
      - "#eb6f92"
      - "#eb6f92"
      - "#f6c177"
      - "#3e8fb0"
      - "#ea9a97"
      - "#9ccfd8"
      - "#c4a7e7"
      - "#c4a7e7"
  - name: "theme-rose-pine"
    colors:
      - "#191724"
      - "#1f1d2e"
      - "#26233a"
      - "#6e6a86"
      - "#908caa"
      - "#e0def4"
      - "#e0def4"
      - "#524f67"
      - "#eb6f92"
      - "#f6c177"
      - "#ebbcba"
      - "#31748f"
      - "#9ccfd8"
      - "#c4a7e7"
      - "#eb6f92"
      - "#95b1ac"
  - name: "theme-selenized-dark"
    colors:
      - "#103c48"
      - "#396775"
      - "#184956"
      - "#396775"
      - "#72898f"
      - "#adbcbc"
      - "#cad8d9"
      - "#cad8d9"
      - "#fa5750"
      - "#ff665c"
      - "#dbb32d"
      - "#75b938"
      - "#41c7b9"
      - "#4695f7"
      - "#f275be"
      - "#f275be"
  - name: "theme-shades-of-purple"
    colors:
      - "#1e1d40"
      - "#686868"
      - "#b362ff"
      - "#686868"
      - "#c7c7c7"
      - "#ffffff"
      - "#ffffff"
      - "#ffffff"
      - "#d90429"
      - "#f92a1c"
      - "#ffe700"
      - "#3ad900"
      - "#00c5c7"
      - "#6943ff"
      - "#ff2c70"
      - "#ff2c70"
  - name: "theme-slate"
    colors:
      - "#262626"
      - "#333333"
      - "#4a4a4a"
      - "#666666"
      - "#afaf87"
      - "#ffffff"
      - "#e5e5e5"
      - "#ffffff"
      - "#ff8787"
      - "#d7875f"
      - "#ffd700"
      - "#87d7ff"
      - "#00cdcd"
      - "#5f87d7"
      - "#cd00cd"
      - "#ffafaf"
  - name: "theme-smyck"
    colors:
      - "#1b1b1b"
      - "#7a7a7a"
      - "#207483"
      - "#7a7a7a"
      - "#a1a1a1"
      - "#f7f7f7"
      - "#f7f7f7"
      - "#f7f7f7"
      - "#b84131"
      - "#d6837c"
      - "#c4a500"
      - "#7da900"
      - "#207383"
      - "#62a3c4"
      - "#ba8acc"
      - "#ba8acc"
  - name: "theme-solarized-osaka"
    colors:
      - "#001419"
      - "#002b36"
      - "#073642"
      - "#586e75"
      - "#657b83"
      - "#93a1a1"
      - "#a9b1b1"
      - "#eee8d5"
      - "#dc322f"
      - "#cb4b16"
      - "#b58900"
      - "#859900"
      - "#2aa198"
      - "#268bd2"
      - "#6c71c4"
      - "#d33682"
  - name: "theme-spacedust"
    colors:
      - "#0a1e24"
      - "#684c31"
      - "#0a385c"
      - "#684c31"
      - "#f0f1ce"
      - "#ecf0c1"
      - "#fefff1"
      - "#fefff1"
      - "#e35b00"
      - "#ff8a3a"
      - "#e3cd7b"
      - "#5cab96"
      - "#06afc7"
      - "#0f548b"
      - "#e35b00"
      - "#e35b00"
  - name: "theme-spacegray-eighties"
    colors:
      - "#222222"
      - "#555555"
      - "#272e35"
      - "#555555"
      - "#efece7"
      - "#bdbaae"
      - "#ffffff"
      - "#ffffff"
      - "#ec5f67"
      - "#ff6973"
      - "#fec254"
      - "#81a764"
      - "#57c2c1"
      - "#5486c0"
      - "#bf83c1"
      - "#bf83c1"
  - name: "theme-srcery"
    colors:
      - "#1c1b19"
      - "#918175"
      - "#fce8c3"
      - "#918175"
      - "#baa67f"
      - "#fce8c3"
      - "#fce8c3"
      - "#fce8c3"
      - "#ef2f27"
      - "#f75341"
      - "#fbb829"
      - "#519f50"
      - "#0aaeb3"
      - "#2c78bf"
      - "#e02c6d"
      - "#e02c6d"
  - name: "theme-terafox"
    colors:
      - "#152528"
      - "#1d3337"
      - "#254147"
      - "#6d7f8b"
      - "#587b7b"
      - "#e6eaea"
      - "#eaeeee"
      - "#cbd9d8"
      - "#e85c51"
      - "#ff8349"
      - "#fda47f"
      - "#7aa4a1"
      - "#a1cdd8"
      - "#5a93aa"
      - "#ad5c7c"
      - "#cb7985"
  - name: "theme-tomorrow-night-bright"
    colors:
      - "#000000"
      - "#404040"
      - "#424242"
      - "#404040"
      - "#ffffff"
      - "#eaeaea"
      - "#ffffff"
      - "#ffffff"
      - "#d54e53"
      - "#d54e53"
      - "#e7c547"
      - "#b9ca4a"
      - "#70c0b1"
      - "#7aa6da"
      - "#c397d8"
      - "#c397d8"
  - name: "theme-treehouse"
    colors:
      - "#191919"
      - "#504332"
      - "#786b53"
      - "#504332"
      - "#786b53"
      - "#786b53"
      - "#ffc800"
      - "#ffc800"
      - "#b2270e"
      - "#ed5d20"
      - "#aa820c"
      - "#44a900"
      - "#b25a1e"
      - "#58859a"
      - "#97363d"
      - "#97363d"
