[default_session]
startup_command = "nvim -c ':Telescope find_files'"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "tmux config"
path = "~/dotfiles/platforms/common/.config/tmux"
startup_command = "nvim tmux.conf"
