[default_session]
startup_command = "nvim -c ':Telescope find_files'"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Downloads ðŸ“¥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "tmux config"
path = "~/dotfiles/common/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/c/dotfiles/.config/tmux/tmux.conf"
